### PR TITLE
(INJI-270) - Fixed that in some languages where few elements are still in English

### PR DESCRIPTION
**Pull request by Anil-kumar-Majji**
**[INJI-270](https://mosip.atlassian.net/browse/INJI-270)** - In the Arabic language few elements are still in English.

[INJI-270]: https://mosip.atlassian.net/browse/INJI-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by swatigoel — CHANGES_REQUESTED** [review]
Why all the texts are starting with small letter now?

**Comment by Anil-kumar-Majji** [comment]
> Why all the texts are starting with small letters now?

Since we are using an object with keys starting with small letters from "**MainLayout**" in the locals.
Ex:- {scan : Scan}

**Comment by Anil-kumar-Majji** [comment]
> I don't see any change in texts in the Arabic language.

They have already existed in all the locals.

**Comment by swatigoel** [comment]
> 

can you please add screenshot after your changes?

**Review by swatigoel — APPROVED** [review]

**Pull request merged**
