### PR TITLE
[INJI-766] Set the backup and restore env variable to true and remove unnecessary full stop in one of the question in help screen

### PR DESCRIPTION
**Pull request by PuBHARGAVI**

### CODE REVIEW

**Review by vharsh — APPROVED** [review]
LGTM

**Review by vharsh — CHANGES_REQUESTED** [review]
HOLD off merging until approved by team

**Review by vijay151096 — APPROVED** [review]
lgtm

**Review by vharsh — APPROVED** [review]
lgtm

**Pull request merged**
